name: Setup
description: Setup Node.js and install dependencies

inputs:
  install:
    description: Whether to install dependencies
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@c336a2788d9774dccfdeb4823a5058ccc9f07453 # v4.3.0

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Cache dependencies
      id: pnpm-cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          **/node_modules
          .pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      if: inputs.install == 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
