import type { IssueSnapshot } from './issue-context.js';
import type { TriageResult } from './triage-schema.js';

export function buildSecurityComment(marker: string, issue: IssueSnapshot, labels: string[], reasons: string[]): string {
  return `${marker}\n\n## AI triage for #${issue.number}\n\nThis issue looks security-sensitive, so posthog-watcher did **not** send the issue contents to pi/OpenAI. Human security review is required.\n\nDetected terms: ${reasons.join(', ') || '(none)'}\n\nSuggested labels: ${labels.length ? labels.map((label) => `\`${label}\``).join(', ') : '_none_'}\n\n---\n_Generated by posthog-watcher-action using deterministic security policy._\n`;
}

export function buildTriageComment(marker: string, issue: IssueSnapshot, triage: TriageResult, labels: string[], prUrl?: string, fixBlockedReason?: string): string {
  const findings = triage.investigation.findings.length
    ? triage.investigation.findings.map((finding) => `- ${finding}`).join('\n')
    : '- No concrete findings yet.';

  const relevantFiles = triage.investigation.relevantFiles.length
    ? triage.investigation.relevantFiles.map((file) => `\`${file}\``).join(', ')
    : '_None identified._';

  return `${marker}

## AI triage for #${issue.number}

**Conclusion:** ${triage.conclusion}  
**Confidence:** ${Math.round(triage.confidence * 100)}%  
**Suggested labels:** ${labels.length ? labels.map((label) => `\`${label}\``).join(', ') : '_none_'}

${triage.maintainerComment || triage.summary}

### Investigation

${findings}

Relevant files: ${relevantFiles}

### Fix assessment

- Straightforward: **${triage.fix.straightforward ? 'yes' : 'no'}**
- Risk: **${triage.fix.risk}**
- Reason: ${triage.fix.reason || '_Not provided._'}
${triage.fix.suggestedApproach ? `- Suggested approach: ${triage.fix.suggestedApproach}\n` : ''}${prUrl ? `\nDraft PR: ${prUrl}\n` : ''}${fixBlockedReason ? `\nFix PR skipped: ${fixBlockedReason}\n` : ''}
### Close proposal

${formatCloseProposal(triage)}

---
_Generated by posthog-watcher-action using pi._
`;
}

function formatCloseProposal(triage: TriageResult): string {
  if (!triage.closeProposal.propose) {
    return 'None. No issue close action was taken.';
  }

  return `Proposal only — no issue close action was taken.\n\n- Category: **${triage.closeProposal.category}**\n- Confidence: **${Math.round(triage.closeProposal.confidence * 100)}%**\n- Reason: ${triage.closeProposal.reason || '_Not provided._'}${triage.closeProposal.canonicalUrl ? `\n- Canonical URL: ${triage.closeProposal.canonicalUrl}` : ''}`;
}
