import * as core from '@actions/core';
import * as github from '@actions/github';
import { createDraftPullRequest, defaultBranch, type Octokit } from './github.js';
import { checkDiffGuardrails, parseNumstat } from './guardrails.js';
import { git, runShell } from './git.js';
import type { ActionInputs } from './inputs.js';
import { formatFixPrompt, type IssueSnapshot } from './issue-context.js';
import { runPi } from './pi-runner.js';
import type { TriageResult } from './triage-schema.js';

export async function maybeCreateFixPr(octokit: Octokit, issue: IssueSnapshot, triage: TriageResult, inputs: ActionInputs): Promise<string | undefined> {
  if (!shouldAttemptFix(triage, inputs)) return undefined;

  const status = await git(['status', '--porcelain']);
  if (status) {
    core.warning('Skipping fix because the checkout has uncommitted changes before pi runs.');
    return undefined;
  }

  const base = defaultBranch();
  const branch = `posthog-watcher/issue-${issue.number}-${github.context.runId}`;

  if (inputs.dryRun) {
    core.info(`[dry-run] Would create branch ${branch}, run pi fix, and open a draft PR.`);
    return undefined;
  }

  await git(['checkout', '-B', branch]);

  await runPi({
    inputs,
    tools: ['read', 'grep', 'find', 'ls', 'bash', 'edit', 'write'],
    prompt: formatFixPrompt(issue, triage),
  });

  if (inputs.validationCommand) {
    core.info(`Running validation command: ${inputs.validationCommand}`);
    await runShell(inputs.validationCommand, process.cwd());
  }

  const numstat = await git(['diff', '--numstat']);
  const stats = parseNumstat(numstat);
  const failures = checkDiffGuardrails(stats, {
    maxChangedFiles: inputs.maxChangedFiles,
    maxDiffLines: inputs.maxDiffLines,
  });

  if (failures.length) {
    core.warning(`Skipping PR because guardrails failed:\n- ${failures.join('\n- ')}`);
    await git(['checkout', '-']);
    return undefined;
  }

  await git(['config', 'user.name', 'posthog-watcher-action']);
  await git(['config', 'user.email', 'posthog-watcher-action@users.noreply.github.com']);
  await git(['add', '--', ...stats.files]);
  await git(['commit', '-m', `Fix #${issue.number}: ${issue.title.slice(0, 80)}`]);
  await git(['push', '--set-upstream', 'origin', branch]);

  const prUrl = await createDraftPullRequest(octokit, {
    title: `Fix #${issue.number}: ${issue.title}`,
    head: branch,
    base,
    body: buildPullRequestBody(issue, triage, stats.files, inputs.validationCommand),
  });

  core.info(`Created draft PR: ${prUrl}`);
  return prUrl;
}

function shouldAttemptFix(triage: TriageResult, inputs: ActionInputs): boolean {
  if (!inputs.allowFix) return false;
  if (inputs.mode === 'triage' || inputs.mode === 'investigate') return false;
  if (triage.confidence < 0.75) return false;
  if (triage.needsMoreInfo) return false;
  if (triage.fix.risk !== 'low') return false;
  return true;
}

function buildPullRequestBody(issue: IssueSnapshot, triage: TriageResult, files: string[], validationCommand: string): string {
  return `Fixes #${issue.number}

Generated by posthog-watcher-action using pi.

## Summary

${triage.summary}

## Triage rationale

${triage.fix.reason}

## Changed files

${files.map((file) => `- \`${file}\``).join('\n')}

## Validation

${validationCommand ? `- \`${validationCommand}\`` : '- No validation command configured.'}
`;
}
