import * as core from '@actions/core';
import { readFile } from 'node:fs/promises';
import { createDraftPullRequest, defaultBranch, findOpenPullRequestForBranch, type Octokit } from './github.js';
import { git } from './git.js';
import type { ActionInputs } from './inputs.js';
import type { IssueSnapshot } from './issue-context.js';
import { runIssueRepair } from './repair-run.js';
import { commitChangesWithGitHubSignature } from './signed-commit.js';
import type { TriageResult } from './triage-schema.js';

export async function maybeCreateFixPr(octokit: Octokit, issue: IssueSnapshot, triage: TriageResult, inputs: ActionInputs): Promise<string | undefined> {
  if (!shouldAttemptFix(triage, inputs)) return undefined;

  const status = await git(['status', '--porcelain']);
  if (status) {
    core.warning('Skipping fix because the checkout has uncommitted changes before pi runs.');
    return undefined;
  }

  const originalRef = await currentCheckoutRef();
  const base = defaultBranch();
  const branch = `posthog-watcher/issue-${issue.number}`;
  const existingPr = await findOpenPullRequestForBranch(octokit, branch);
  const existingRemoteBranch = await remoteBranchExists(branch);

  if (inputs.dryRun) {
    core.info(`[dry-run] Would ${existingPr ? `update existing PR ${existingPr.url}` : existingRemoteBranch ? `reuse remote branch ${branch} and open a draft PR` : `create branch ${branch} and open a draft PR`}.`);
    return existingPr?.url;
  }

  try {
    let expectedHeadOid: string;
    if (existingPr || existingRemoteBranch) {
      core.info(existingPr ? `Reusing existing draft PR branch ${branch}: ${existingPr.url}` : `Reusing existing remote branch ${branch}.`);
      await checkoutExistingBranch(branch);
      expectedHeadOid = await git(['rev-parse', `origin/${branch}`]);
    } else {
      await git(['checkout', '-B', branch]);
      expectedHeadOid = await git(['rev-parse', 'HEAD']);
    }

    const pullRequestTemplate = await readPullRequestTemplate();
    const repair = await runIssueRepair(issue, triage, inputs);
    if (!repair) {
      return undefined;
    }

    const commit = await commitChangesWithGitHubSignature(octokit, {
      branch,
      message: `Fix #${issue.number}: ${issue.title.slice(0, 80)}`,
      expectedHeadOid,
      createBranch: !existingPr && !existingRemoteBranch,
    });
    core.info(`Created GitHub-signed commit: ${commit.url}`);

    if (existingPr) {
      core.info(`Updated existing draft PR: ${existingPr.url}`);
      return existingPr.url;
    }

    const prUrl = await createDraftPullRequest(octokit, {
      title: `fix: ${issue.title}`,
      head: branch,
      base,
      body: buildPullRequestBody(issue, triage, repair.files, inputs.validationCommand, pullRequestTemplate),
    });

    core.info(`Created draft PR: ${prUrl}`);
    return prUrl;
  } finally {
    await restoreCheckout(originalRef);
  }
}

async function currentCheckoutRef(): Promise<string> {
  const branch = await git(['rev-parse', '--abbrev-ref', 'HEAD']);
  return branch === 'HEAD' ? git(['rev-parse', 'HEAD']) : branch;
}

async function restoreCheckout(originalRef: string): Promise<void> {
  await git(['reset', '--hard', 'HEAD']).catch((error) => core.warning(`Failed to reset worktree before restore: ${error instanceof Error ? error.message : String(error)}`));
  await git(['checkout', originalRef]).catch((error) => core.warning(`Failed to restore original checkout ${originalRef}: ${error instanceof Error ? error.message : String(error)}`));
}

async function remoteBranchExists(branch: string): Promise<boolean> {
  return Boolean(await git(['ls-remote', '--heads', 'origin', branch]));
}

async function checkoutExistingBranch(branch: string): Promise<void> {
  await git(['fetch', 'origin', `refs/heads/${branch}:refs/remotes/origin/${branch}`]);
  await git(['checkout', '-B', branch, `origin/${branch}`]);
}

function shouldAttemptFix(triage: TriageResult, inputs: ActionInputs): boolean {
  if (!inputs.allowFix) return false;
  if (inputs.mode === 'triage' || inputs.mode === 'investigate') return false;
  if (triage.confidence < 0.75) return false;
  if (triage.needsMoreInfo) return false;
  if (triage.fix.risk !== 'low') return false;
  return true;
}

async function readPullRequestTemplate(): Promise<string | undefined> {
  try {
    return await readFile('.github/pull_request_template.md', 'utf8');
  } catch (error) {
    if (isNotFoundError(error)) return undefined;
    throw error;
  }
}

function isNotFoundError(error: unknown): boolean {
  return typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT';
}

function buildPullRequestBody(issue: IssueSnapshot, triage: TriageResult, files: string[], validationCommand: string, template?: string): string {
  const watcherBody = `Fixes #${issue.number}

Generated by posthog-watcher-action using pi.

## Summary

${triage.summary}

## Triage rationale

${triage.fix.reason}

## Changed files

${files.map((file) => `- \`${file}\``).join('\n')}

## Validation

${validationCommand ? `- \`${validationCommand}\`` : '- No validation command configured.'}
`;

  return template ? `${template.trimEnd()}\n\n---\n\n${watcherBody}` : watcherBody;
}
