import type { IssueSnapshot } from './issue-context.js';
import type { TriageResult } from './triage-schema.js';

const TEMPLATE_MARKERS = {
  problem: '<!-- posthog-watcher:problem -->',
  changes: '<!-- posthog-watcher:changes -->',
  validation: '<!-- posthog-watcher:validation -->',
  agentContext: '<!-- posthog-watcher:agent-context -->',
} as const;

export interface PullRequestBodyInput {
  issue: IssueSnapshot;
  triage: TriageResult;
  files: string[];
  validationCommand: string;
  template?: string;
  humanDriver?: string;
  affectedPackages?: string[];
  existingFiles?: string[];
}

export function buildPullRequestBody({ issue, triage, files, validationCommand, template, humanDriver, affectedPackages = [], existingFiles = [] }: PullRequestBodyInput): string {
  const problem = `Fixes #${issue.number}\n\n${triage.summary}`;
  const validation = validationCommand ? `- \`${validationCommand}\` (passed)` : '- No validation command configured.';
  const hasValidationSlot = Boolean(template?.includes(TEMPLATE_MARKERS.validation) || templateHasHeading(template, 'Validation'));
  const changes = `${triage.fix.reason}\n\n### Changed files\n\n${formatFiles(files)}${hasValidationSlot ? '' : `\n\n### Validation\n\n${validation}`}`;
  const agentContext = formatAgentContext(humanDriver);
  const watcherBody = `${problem}\n\nGenerated by posthog-watcher-action using pi.\n\n## Summary\n\n${triage.summary}\n\n## Triage rationale\n\n${triage.fix.reason}\n\n## Changed files\n\n${formatFiles(files)}\n\n## Validation\n\n${validation}\n`;

  if (!template?.trim()) return watcherBody;

  let body = template.trimEnd();
  let problemPlaced = replaceMarker(body, TEMPLATE_MARKERS.problem, problem);
  body = problemPlaced.body;
  let changesPlaced = replaceMarker(body, TEMPLATE_MARKERS.changes, changes);
  body = changesPlaced.body;

  if (!problemPlaced.replaced) {
    problemPlaced = insertUnderHeading(body, 'Problem', problem);
    body = problemPlaced.body;
  }
  if (!changesPlaced.replaced) {
    changesPlaced = insertUnderHeading(body, 'Changes', changes);
    body = changesPlaced.body;
  }

  const validationMarker = replaceMarker(body, TEMPLATE_MARKERS.validation, validation);
  body = validationMarker.body;
  if (!validationMarker.replaced) body = insertUnderHeading(body, 'Validation', validation).body;

  const agentMarker = replaceMarker(body, TEMPLATE_MARKERS.agentContext, agentContext);
  body = agentMarker.body;
  if (!agentMarker.replaced) body = populateAgentContext(body, humanDriver);

  body = markVerifiedChecklistItems(body, existingFiles, affectedPackages);

  if (problemPlaced.replaced && changesPlaced.replaced) return `${body}\n`;
  return `${body}\n\n---\n\n${watcherBody}`;
}

function formatFiles(files: string[]): string {
  return files.map((file) => `- \`${file}\``).join('\n');
}

function formatAgentContext(humanDriver?: string): string {
  const autonomy = humanDriver ? 'Human-driven (agent-assisted)' : 'Fully autonomous';
  const attribution = humanDriver ? ` The work was directed by @${humanDriver}, who is assigned as the DRI.` : '';
  return `**Autonomy:** ${autonomy}\n\nGenerated by posthog-watcher-action using pi.${attribution}`;
}

function replaceMarker(body: string, marker: string, content: string): { body: string; replaced: boolean } {
  if (!body.includes(marker)) return { body, replaced: false };
  return { body: body.replace(marker, content), replaced: true };
}

function insertUnderHeading(body: string, heading: string, content: string): { body: string; replaced: boolean } {
  const lines = body.split('\n');
  const headingIndex = findVisibleHeadingIndex(lines, heading);
  if (headingIndex === -1) return { body, replaced: false };
  lines.splice(headingIndex + 1, 0, '', content);
  return { body: lines.join('\n'), replaced: true };
}

function normalizeHeading(line: string): string {
  const match = line.match(/^#{1,6}\s+(.+)$/);
  if (!match) return '';
  return (match[1] ?? '')
    .replace(/^[^\p{L}\p{N}]+/u, '')
    .trim()
    .toLowerCase();
}

function templateHasHeading(template: string | undefined, heading: string): boolean {
  return template ? findVisibleHeadingIndex(template.split('\n'), heading) !== -1 : false;
}

function findVisibleHeadingIndex(lines: string[], heading: string): number {
  let inHtmlComment = false;
  let fence: { character: string; length: number } | undefined;

  for (const [index, line] of lines.entries()) {
    const visibleLine = stripHtmlComments(line, (value) => {
      inHtmlComment = value;
    }, inHtmlComment);
    const fenceMatch = visibleLine.trimStart().match(/^(`{3,}|~{3,})/);
    if (fenceMatch) {
      const marker = fenceMatch[1] ?? '';
      if (!fence) {
        fence = { character: marker[0] ?? '', length: marker.length };
      } else if (marker[0] === fence.character && marker.length >= fence.length) {
        fence = undefined;
      }
      continue;
    }
    if (!fence && normalizeHeading(visibleLine) === heading.toLowerCase()) return index;
  }
  return -1;
}

function stripHtmlComments(line: string, setCommentState: (value: boolean) => void, initialState: boolean): string {
  let inComment = initialState;
  let remaining = line;
  let visible = '';

  while (remaining) {
    if (inComment) {
      const end = remaining.indexOf('-->');
      if (end === -1) break;
      inComment = false;
      remaining = remaining.slice(end + 3);
      continue;
    }

    const start = remaining.indexOf('<!--');
    if (start === -1) {
      visible += remaining;
      break;
    }
    visible += remaining.slice(0, start);
    inComment = true;
    remaining = remaining.slice(start + 4);
  }

  setCommentState(inComment);
  return visible;
}

function populateAgentContext(body: string, humanDriver?: string): string {
  const autonomy = humanDriver ? 'Human-driven (agent-assisted)' : 'Fully autonomous';
  const attribution = humanDriver ? ` The work was directed by @${humanDriver}, who is assigned as the DRI.` : '';
  const autonomyLine = /^\*\*Autonomy:\*\*.*$/m;
  if (autonomyLine.test(body)) {
    return body.replace(autonomyLine, `**Autonomy:** ${autonomy}\n\nGenerated by posthog-watcher-action using pi.${attribution}`);
  }

  const inserted = insertUnderHeading(body, 'Agent context', formatAgentContext(humanDriver));
  return inserted.body;
}

function markVerifiedChecklistItems(body: string, existingFiles: string[], affectedPackages: string[]): string {
  const hasTests = existingFiles.some((file) => /(^|\/)(tests?|__tests__)(\/|$)|\.(test|spec)\.[^/]+$/i.test(file));
  const packageNames = new Set(affectedPackages.map((name) => name.toLowerCase()));

  return body
    .split('\n')
    .map((line) => {
      const match = line.match(/^(\s*)- \[ \] (.+)$/);
      if (!match) return line;
      const indentation = match[1] ?? '';
      const label = (match[2] ?? '').trim();
      const normalizedLabel = label.replace(/\s+\([^)]*\)\s*$/, '').toLowerCase();
      const verified = (hasTests && normalizedLabel === 'tests for new code') || packageNames.has(normalizedLabel);
      return verified ? `${indentation}- [x] ${label}` : line;
    })
    .join('\n');
}
